#spring.application.name=SpringSecurity
##spring.data.mongodb.uri=mongodb+srv://drustantmetar_db_user:20rtB4Zty3Eq9VJ1@cluster0.neoobzh.mongodb.net/?appName=Cluster0
#spring.data.mongodb.host=127.0.0.1
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=MyDB
#server.port=8082
#spring.data.mongodb.auto-index-creation=true
##spring.security.user.enabled=false
