spring:
  application:
    name:SpringSecurity

  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.6.0
      host : 127.0.0.1
      port: 27017
      database : journal
      index-creation: true


server:
  port: 8085